export const stackLogos = [
  { name: "TypeScript", logo: "/stack/typescript-icon-svgrepo-com.svg" },
  { name: "JavaScript", logo: "/stack/javascript-svgrepo-com.svg" },
  { name: "Html5", logo: "/stack/html-5-svgrepo-com.svg" },
  { name: "CSS3", logo: "/stack/css-3-svgrepo-com.svg" },
  { name: "SASS", logo: "/stack/sass-1.svg" },
  { name: "React", logo: "/stack/react-svgrepo-com.svg" },
  { name: "Angular", logo: "/stack/angular-icon-svgrepo-com.svg" },
  { name: "Next", logo: "/stack/nextjs-svgrepo-com.svg" },
  { name: "Node", logo: "/stack/nodejs-1.svg" },
  { name: "Python", logo: "/stack/python-svgrepo-com.svg" },
  { name: "Slack", logo: "/stack/slack-svgrepo-com.svg" },
  { name: "Vue", logo: "/stack/vue-svgrepo-com.svg" },
  { name: "Git", logo: "/stack/git-icon.svg" },
  { name: "GitHub", logo: "/stack/github-icon-1.svg" },
  { name: "AWS", logo: "/stack/aws-2.svg" },
  { name: "Docker", logo: "/stack/docker-4.svg" },
  { name: "FastAPI", logo: "/stack/fastapi-1.svg" },
  { name: "Figma", logo: "/stack/figma-svgrepo-com.svg" },
  { name: "Flask", logo: "/stack/flask-svgrepo-com.svg" },
  { name: "GCP", logo: "/stack/google-cloud-1.svg" },
  { name: "Lighthouse", logo: "/stack/google-lighthouse.svg" },
  { name: "Express.js", logo: "/stack/express-svgrepo-com.svg" },
  { name: "CircleCI", logo: "/stack/heroku-4.svg" },
  { name: "Heroku", logo: "/stack/circleci.svg" },
  { name: "PostgreSQL", logo: "/stack/postgresql-svgrepo-com.svg" },
  { name: "Vercel", logo: "/stack/vercel-logo-svgrepo-com.svg" },
  { name: "Linux", logo: "/stack/linux-tux.svg" },
  { name: "Cypress", logo: "/stack/cypress-1.svg" },
  { name: "Jest", logo: "/stack/jest-svgrepo-com.svg" },
  { name: "Webpack", logo: "/stack/webpack-icon.svg" },
  { name: "Sanity", logo: "/stack/sanity.svg" },
];

export const projects = [
  {
    name: "Menalated",
    short: "menalated",
    image: "/menalated/men-desk.svg",
    year: "2025",
    link: "/projects/menalated",
  },
  {
    name: "St. Luke Clinic",
    short: "stluke",
    image: "/luke/luke-desk.jpeg",
    year: "2024",
    link: "/projects/stluke",
  },
  {
    name: "AFPS Event",
    short: "afps",
    image: "/afps/afps-desk.jpeg",
    year: "2023",
    link: "/projects/afps",
  },
  {
    name: "Cinema Scheduler",
    short: "scheduler",
    image: "/scheduler/sched-desk.svg",
    year: "2023",
    link: "/projects/scheduler",
  },
  {
    name: "ZROverse",
    short: "zroverse",
    image: "/zro/zro-desk.jpeg",
    year: "2022",
    link: "/projects/zroverse",
  },
  {
    name: "AITI Alumni Platform",
    short: "aiti",
    image: "/aiti/aiti-desk.jpeg",
    year: "2021",
    link: "/projects/aiti",
  },
];
